### ISSUE TITLE
Doesn't seem to work

### ISSUE THREAD

**Issue by unknowndomain** [natcl/node-red-contrib-lfo#1]
I presume this node is supposed to just work i.e. you don't have to trigger it, because the notes don't mention that, and in fact the input is for configuring the node.

Taking that assumption I passed the output to a debug node and a range node, then into a GPIO output, but this doesn't seem to work, the debug node doesn't receive any data, nor does the range or GPIO nodes.

If you want to try what I've been using here is the code in Node-RED that you can import.
````
[{"id":"d239720.985d89","type":"tab","label":"Flow 1","disabled":false,"info":""},{"id":"189b4787.774018","type":"rpi-gpio out","z":"d239720.985d89","name":"","pin":"16","set":false,"level":"0","freq":"50","out":"pwm","x":600,"y":140,"wires":[]},{"id":"32e1887.3852778","type":"range","z":"d239720.985d89","minin":"-1","maxin":"1","minout":"0","maxout":"100","action":"scale","round":true,"property":"payload","name":"","x":440,"y":140,"wires":[["189b4787.774018"]]},{"id":"b9d5cbc5.c2de28","type":"lfo-node","z":"d239720.985d89","name":"","waveform":"triangle","frequency":"25","samplingrate":20,"x":290,"y":140,"wires":[["32e1887.3852778","52203f41.699d6"]]},{"id":"52203f41.699d6","type":"debug","z":"d239720.985d89","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","x":450,"y":200,"wires":[]}]
````

**Comment by natcl** [comment]
As stated in the help you need to send an input to trigger the node:

Sending a number as msg.payload will change the frequency of the LFO.
Sending the string 'stop' as msg.payload will stop the output. Sending
anything else will start the waveform.

Le mar. 2 avr. 2019, à 16 h 49, Tom Lynch <notifications@github.com> a
écrit :

**Comment by unknowndomain** [comment]
Now look who looks like a bloody idiot!

Sorry and thanks! :D

**Comment by natcl** [comment]
No worries!
